name = "Hugo Novela"
license = "MIT"
licenselink = "https://github.com/forestryio/hugo-theme-novela/blob/master/LICENSE"
description = "A Hugo port of the Novela theme by Narative"
homepage = "https://hugo-novela-forestry.netlify.com/"
tags = ["blog"]
features = ["dark mode", "grid view"]
min_version = "0.65.0"

[author]
    name = "Vedant"
    homepage = "https://www.thenewdynamic.com/"

# If porting an existing theme
[original]
    author = "Vedant"
    homepage = "https://blog.vedant.cloud"
    repo = "https://github.com/narative/gatsby-theme-novela"
